const path = require('path');

const PIN_MONEDERO = 22;
const PIN_SENSOR_ABAJO = 5;
const PIN_SENSOR_ARRIBA = 6;
const PIN_ENERGIA = 17;

const DEBOUNCE_COIN_MS = 500;
const MAX_PUNCH_WINDOW_MS = 150;
const MIN_PUNCH_DT_US = 2000;

const DIFFICULTY_FACTOR = 1.0;
const SCORE_NOISE = 5;
const MAX_SCORE = 999;
const SCORE_MIN = 0;
const SCORE_HALF_TIME_MS = 12;
const SCORE_STEEPNESS = 2.5;

const STATE_ATTRACT = 'attract';
const STATE_WAITING = 'waiting';
const STATE_COUNTDOWN = 'countdown';
const STATE_READY = 'ready';
const STATE_ANIMATING = 'animating';
const STATE_RESULT = 'result';

const COUNTDOWN_DURATION_MS = 3000;
const ANIMATION_DURATION_MS = 1600;
const RESULT_DISPLAY_MS = 4000;
const READY_TIMEOUT_MS = 15000;

const RECORDS_FILE = path.join(__dirname, '..', 'records.txt');
const DEFAULT_RECORDS = [850, 720, 500];

const IOT_BACKEND_URL = 'http://72.61.74.156:3000/api/iot/data';
const MACHINE_ID = 'Maquina_Boxeo_K11';
const IOT_PING_INTERVAL_MS = 20000;
const IOT_RETRY_INTERVAL_MS = 5000;
const IOT_OFFLINE_FILE = path.join(__dirname, '..', 'iot_queue.txt');
const WDT_ENABLED = true;
const WDT_FEED_INTERVAL_MS = 8000;
const WDT_DEVICE = '/dev/watchdog';
const POWER_SENSOR_DEBOUNCE_MS = 300;

module.exports = {
  PIN_MONEDERO,
  PIN_SENSOR_ABAJO,
  PIN_SENSOR_ARRIBA,
  PIN_ENERGIA,
  DEBOUNCE_COIN_MS,
  MAX_PUNCH_WINDOW_MS,
  MIN_PUNCH_DT_US,
  DIFFICULTY_FACTOR,
  SCORE_NOISE,
  MAX_SCORE,
  SCORE_MIN,
  SCORE_HALF_TIME_MS,
  SCORE_STEEPNESS,
  STATE_ATTRACT,
  STATE_WAITING,
  STATE_COUNTDOWN,
  STATE_READY,
  STATE_ANIMATING,
  STATE_RESULT,
  COUNTDOWN_DURATION_MS,
  ANIMATION_DURATION_MS,
  RESULT_DISPLAY_MS,
  READY_TIMEOUT_MS,
  RECORDS_FILE,
  DEFAULT_RECORDS,
  IOT_BACKEND_URL,
  MACHINE_ID,
  IOT_PING_INTERVAL_MS,
  IOT_RETRY_INTERVAL_MS,
  IOT_OFFLINE_FILE,
  WDT_ENABLED,
  WDT_FEED_INTERVAL_MS,
  WDT_DEVICE,
  POWER_SENSOR_DEBOUNCE_MS,
};
